/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Page_d_accueil (void);
GtkWidget* create_Gestion_des___lections_et_des_utilisateurs (void);
GtkWidget* create_Gestion_des_bureaux_de_vote (void);
GtkWidget* create_Gestion_des_listes___lectorales (void);
GtkWidget* create_menu (void);
