/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Page_d_accueil;
  GtkWidget *Gestion_des___lections_et_des_utilisateurs;
  GtkWidget *Gestion_des_bureaux_de_vote;
  GtkWidget *Gestion_des_listes___lectorales;
  GtkWidget *menu;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Page_d_accueil = create_Page_d_accueil ();
  gtk_widget_show (Page_d_accueil);
  /*Gestion_des___lections_et_des_utilisateurs = create_Gestion_des___lections_et_des_utilisateurs ();
  gtk_widget_show (Gestion_des___lections_et_des_utilisateurs);
  Gestion_des_bureaux_de_vote = create_Gestion_des_bureaux_de_vote ();
  gtk_widget_show (Gestion_des_bureaux_de_vote);
  Gestion_des_listes___lectorales = create_Gestion_des_listes___lectorales ();
  gtk_widget_show (Gestion_des_listes___lectorales);
  menu = create_menu ();
  gtk_widget_show (menu);*/

  gtk_main ();
  return 0;
}

